### ISSUE TITLE
[Feature Request] Add a section featuring all discussed crates in "this week in bevy" playlist

### ISSUE THREAD

**Issue by kettei-sproutty** [rust-adventure/thisweekinbevy#15]
Hi all!

I would like to propose a section where we can stay up-to-date about crates discussed in the YouTube playlist.
I sometimes happen to need a crate that I saw in a video but don't really remember which one.

Honestly I have no really an idea to which could be the best way to organize this section, if something like:

```toml
name = "bevy_*"
latest_supported_version = "0.15"
category = []
showcase = "video url"
uri = ""
```

or something more automatized and low maintaining using directly [crates.io API (example)](https://crates.io/api/v1/crates/bevy)

I understand that this can be really extra-work and not really easy to maintain, but let me know what you think about it!

P.S. Happy new year!
